In [2]:
import sys
import os
import warnings

sys.path.append(
    os.path.abspath(os.path.join(os.path.dirname(os.path.realpath("__file__")), ".."))
)

warnings.simplefilter(action="ignore", category=FutureWarning)

In [11]:
import pandas as pd

from handyman import (
    get_company_info,
    get_officers,
    get_prices,
    get_analyst_price_targets,
    get_analyst_recommendations,
    get_analyst_upgrades_downgrades,
    get_options,
    get_institutional_holders,
    get_major_holders,
    get_insider_transactions,
    get_fundamentals,
    get_eps_revisions,
    get_earnings_surprises,
    get_eps_estimates,
    get_revenue_estimates,
    get_growth_estimates,
)

tickers = ["AAPL", "MSFT", "GE", "NVDA", "JPM", "META", "FOX"]

In [25]:
get_company_info(
    tickers=["GE"],
    # get_latest=True
)[["DATE", "TICKER", "MARKETCAP"]]

         DATE TICKER     MARKETCAP
0  2025-11-22     GE           NaN
1  2025-11-24     GE           NaN
2  2025-12-02     GE           NaN
3  2025-12-08     GE           NaN
4  2025-12-15     GE           NaN
5  2025-12-22     GE           NaN
6  2025-12-30     GE           NaN
7  2026-01-05     GE           NaN
8  2026-01-12     GE  3.437626e+11
9  2026-01-20     GE  3.312176e+11
10 2026-01-26     GE  3.112334e+11
11 2026-02-02     GE  3.256316e+11
12 2026-02-09     GE  3.341017e+11
13 2026-02-17     GE  3.450085e+11
14 2026-03-02     GE  3.646914e+11
15 2026-03-03     GE  3.524555e+11
16 2026-03-04     GE  3.584363e+11
17 2026-03-04     GE  3.584363e+11
18 2026-03-05     GE  3.449136e+11
19 2026-03-06     GE  3.408209e+11

In [17]:
get_growth_estimates(tickers="AAPL").sort_values("DATE")

         DATE TICKER PERIOD  STOCKTREND  INDEXTREND ESTIMATE_TYPE
2  2026-02-27   AAPL     0q      0.1843      0.1333        GROWTH
3  2026-02-27   AAPL    +1q      0.1045      0.1086        GROWTH
4  2026-02-27   AAPL     0y      0.1398      0.1463        GROWTH
5  2026-02-27   AAPL    +1y      0.0937      0.1580        GROWTH
6  2026-02-27   AAPL    LTG         NaN      0.1220        GROWTH
9  2026-03-02   AAPL    +1q      0.1039      0.1086        GROWTH
7  2026-03-02   AAPL     0q      0.1840      0.1333        GROWTH
8  2026-03-02   AAPL     0y      0.1397      0.1463        GROWTH
10 2026-03-02   AAPL    +1y      0.0944      0.1580        GROWTH
16 2026-03-03   AAPL    +1q      0.1015      0.1085        GROWTH
15 2026-03-03   AAPL     0q      0.1849      0.1318        GROWTH
18 2026-03-03   AAPL    +1y      0.0960      0.1579        GROWTH
17 2026-03-03   AAPL     0y      0.1392      0.1466        GROWTH
12 2026-03-04   AAPL    +1q      0.1015      0.1091        GROWTH
13 2026-03-04   AAPL     0y      0.1392      0.1473        GROWTH
14 2026-03-04   AAPL    +1y      0.0960      0.1575        GROWTH
11 2026-03-04   AAPL     0q      0.1849      0.1321        GROWTH
1  2026-03-05   AAPL     0y      0.1392      0.1339        GROWTH
0  2026-03-05   AAPL     0q      0.1853      0.1445        GROWTH

In [14]:
get_major_holders(tickers="AAPL").sort_values("DATE")

         DATE TICKER                         INDEX       VALUE
3  2026-02-27   AAPL           insidersPercentHeld     0.01840
4  2026-02-27   AAPL       institutionsPercentHeld     0.65176
5  2026-02-27   AAPL  institutionsFloatPercentHeld     0.66397
6  2026-02-27   AAPL             institutionsCount  7491.00000
7  2026-03-03   AAPL  institutionsFloatPercentHeld     0.66403
8  2026-03-03   AAPL       institutionsPercentHeld     0.65181
9  2026-03-03   AAPL             institutionsCount  7494.00000
10 2026-03-04   AAPL           insidersPercentHeld     0.01637
11 2026-03-04   AAPL       institutionsPercentHeld     0.65191
12 2026-03-04   AAPL  institutionsFloatPercentHeld     0.66276
13 2026-03-04   AAPL             institutionsCount  7498.00000
0  2026-03-05   AAPL       institutionsPercentHeld     0.65200
1  2026-03-05   AAPL  institutionsFloatPercentHeld     0.66285
2  2026-03-05   AAPL             institutionsCount  7514.00000

In [ ]:
from handyman import get_index_holdings, get_llm_holdings

get_index_holdings(start_date="2026-03-05").sort_values("INDEX")

,DATE,INDEX,TICKER,NAME,MARKET_VALUE,WEIGHT,QUANTITY,PRICE,LOCATION,EXCHANGE,CURRENCY,FX_RATE
752,2026-03-05,Russell 1000,HLT,HILTON WORLDWIDE HOLDINGS INC,5.047785e+07,0.001103,165550.0,304.91,United States,NYSE,USD,1.0
795,2026-03-05,Russell 1000,IRM,IRON MOUNTAIN INC,2.310698e+07,0.000505,214271.0,107.84,United States,NYSE,USD,1.0
794,2026-03-05,Russell 1000,IRDM,IRIDIUM COMMUNICATIONS INC,1.681460e+06,0.000037,68603.0,24.51,United States,NASDAQ,USD,1.0
793,2026-03-05,Russell 1000,IR,INGERSOLL RAND INC,2.687688e+07,0.000587,292649.0,91.84,United States,NYSE,USD,1.0
792,2026-03-05,Russell 1000,IQV,IQVIA HOLDINGS INC,2.176575e+07,0.000476,122362.0,177.88,United States,NYSE,USD,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
212,2026-03-05,S&P 500,RTX,RTX CORP,3.549093e+09,0.004771,16995946.0,208.82,United States,NYSE,USD,1.0
213,2026-03-05,S&P 500,RVTY,REVVITY INC,1.414210e+08,0.000190,1435892.0,98.49,United States,NYSE,USD,1.0
214,2026-03-05,S&P 500,SBAC,SBA COMMUNICATIONS REIT CORP CLASS,2.653327e+08,0.000357,1350775.0,196.43,United States,NASDAQ,USD,1.0
207,2026-03-05,S&P 500,ROK,ROCKWELL AUTOMATION INC,5.455584e+08,0.000733,1423134.0,383.35,United States,NYSE,USD,1.0
1505,2026-03-05,S&P 500,FFIV,F5 INC,2.092101e+08,0.000281,731197.0,286.12,United States,NASDAQ,USD,1.0

In [22]:
get_llm_holdings(get_latest=True, llms="CLAUDE")

,TICKER,COMPANY_NAME,SECTOR,WEIGHT,INVESTMENT_THESIS,DATE,STRATEGY
0,MSFT,Microsoft Corporation,Technology,0.069815,"Microsoft Azure, Office 365, and GitHub create...",2026-03-02,CLAUDE
1,NVDA,NVIDIA Corporation,Technology,0.065709,CUDA ecosystem developer lock-in sustains GPU ...,2026-03-02,CLAUDE
2,AAPL,Apple Inc.,Technology,0.059548,Apple's 2.2B+ active device ecosystem generate...,2026-03-02,CLAUDE
3,ASML,ASML Holding N.V.,Technology,0.058522,ASML holds a global monopoly on EUV lithograph...,2026-03-02,CLAUDE
4,V,Visa Inc.,Financials,0.055441,Visa's network scales with global GDP and the ...,2026-03-02,CLAUDE
5,MA,Mastercard Incorporated,Financials,0.053388,Mastercard shares Visa's structural advantages...,2026-03-02,CLAUDE
6,LLY,Eli Lilly and Company,Healthcare,0.053388,Tirzepatide addresses a $100B+ addressable mar...,2026-03-02,CLAUDE
7,COST,Costco Wholesale Corporation,Consumer Staples,0.051335,Costco's membership model monetizes loyalty di...,2026-03-02,CLAUDE
8,GOOGL,Alphabet Inc.,Technology,0.051335,Google Search advantage is reinforced by the q...,2026-03-02,CLAUDE
9,AMZN,"Amazon.com, Inc.",Technology,0.051335,AWS global cloud infrastructure leadership is ...,2026-03-02,CLAUDE
10,BRK-B,Berkshire Hathaway Inc.,Financials,0.046201,Berkshire's float-funded model and diversified...,2026-03-02,CLAUDE
11,ISRG,"Intuitive Surgical, Inc.",Healthcare,0.040041,Da Vinci installed-base flywheel converts capi...,2026-03-02,CLAUDE
12,SPGI,S&P Global Inc.,Financials,0.037988,S&P Global operates a ratings oligopoly and be...,2026-03-02,CLAUDE
13,ABBV,AbbVie Inc.,Healthcare,0.036961,AbbVie successfully navigated Humira biosimila...,2026-03-02,CLAUDE
14,MCO,Moody's Corporation,Financials,0.035934,Moody's ratings franchise shares SPGI's mandat...,2026-03-02,CLAUDE
15,TMO,Thermo Fisher Scientific Inc.,Healthcare,0.034908,Thermo Fisher is the picks-and-shovels provide...,2026-03-02,CLAUDE
16,TXN,Texas Instruments Incorporated,Technology,0.033881,TI analog and embedded processing chips are em...,2026-03-02,CLAUDE
17,DHR,Danaher Corporation,Healthcare,0.031827,Danaher Business System operating discipline i...,2026-03-02,CLAUDE
18,MSCI,MSCI Inc.,Financials,0.030801,MSCI index licensing used by $15T+ in passive ...,2026-03-02,CLAUDE
19,INTU,Intuit Inc.,Technology,0.027721,TurboTax and QuickBooks embed deep workflow de...,2026-03-02,CLAUDE
20,IDXX,"IDEXX Laboratories, Inc.",Healthcare,0.026694,IDEXX near-monopoly in veterinary diagnostics ...,2026-03-02,CLAUDE
21,ADYEN.AS,Adyen N.V.,Financials,0.024640,Adyen's unified payments platform serves globa...,2026-03-02,CLAUDE
22,HEIA.AS,Heineken N.V.,Consumer Staples,0.022588,Heineken is a global beer duopolist with domin...,2026-03-02,CLAUDE

In [ ]:
# from connectors.azure_data_source import default_azure_data_source
# from sql.script_factory import SQLClient

# engine = default_azure_data_source.get_engine()
# sql_client = SQLClient()

# query = sql_client.build_select_all_query(table_name="address")
# address_df = default_azure_data_source.read_sql_table(engine=engine, query=query)

# address_df

,ADDRESS1,CITY,COUNTRY,LAT,LON
0,2788 San Tomas Expressway,Santa Clara,United States,37.370544,-121.967081
1,One Apple Park Way,Cupertino,United States,37.335651,-122.014050
2,One Microsoft Way,Redmond,United States,47.641070,-122.126882
3,410 Terry Avenue North,Seattle,United States,47.622298,-122.336500
4,3421 Hillview Ave,Palo Alto,United States,37.399027,-122.144416
...,...,...,...,...,...
1035,229 West 43rd Street,New York,United States,40.757472,-73.987472
1036,10500 Liberty Parkway,Birmingham,United States,33.477218,-86.703816
1037,4114 Center at North Hills Street,Raleigh,United States,35.837166,-78.644073
1038,601 Merritt Seven,Norwalk,United States,41.117597,-73.407897
1039,900 Sylvan Avenue,Englewood Cliffs,United States,40.898686,-73.939288